'use strict';function handleSuccess(a){console.log("Success arguments");console.log(a)}function handleError(a){console.log("Error");console.log(a)}
angular.module("homePage",[]).controller("HomePageCtrl",["$scope",function(a){a.card={name:"Episodes Watched"};a.selectedIndex=1;a.menuActions=[{name:"Verify User",apiIndex:0},{name:"Get Animelist From MAL",apiIndex:1},{name:"Get Animelist",apiIndex:1}];a.onMenuClick=function(a){0===a&&chiika.callApi(0,{user:"arkenthera",pass:"123asd456"},handleSuccess,handleError);1===a&&chiika.callApi(1,"",handleSuccess,handleError);2===a&&chiika.callApi(2,"",handleSuccess,handleError)}}]).directive("homePageDir",
function(){return{restrict:"E",templateUrl:"homepage.html"}});
angular.module("animeList",[]).controller("AnimeListCtrl",["$scope","$q","$timeout",function(a,b,c){a.selected=[];a.query={order:"title",limit:5,page:1};a.test="5";a.watchingList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",
score:"-",season:"Fall 2015"},{title:"Gakusen Asterisk",progress:{value:.9},progressString:"24/25",type:"Tv",score:"-",season:"Fall 2015"}]};a.completedList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",score:"-",season:"Fall 2015"},
{title:"Gakusen Asterisk",progress:{value:.9},progressString:"24/25",type:"Tv",score:"-",season:"Fall 2015"}]};a.droppedList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Gakusen Asterisk",
progress:{value:.9},progressString:"24/25",type:"Tv",score:"-",season:"Fall 2015"}]};a.onHoldList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Gakusen Asterisk",progress:{value:.9},progressString:"24/25",
type:"Tv",score:"-",season:"Fall 2015"}]};a.ptwList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Gakusen Asterisk",progress:{value:.9},progressString:"24/25",type:"Tv",score:"-",season:"Fall 2015"}]};
a.getTypes=function(){return["Tv"]};a.onorderchange=function(a){var d=b.defer();c(function(){d.resolve()},2E3);return d.promise};a.onpagechange=function(a,d){var f=b.defer();c(function(){f.resolve()},2E3);return f.promise}}]).directive("animeListDir",function(){return{scope:{},restrict:"E",templateUrl:"animeList.html",controller:"AnimeListCtrl",controllerAs:"ctrl",replace:!1}});
angular.module("animeTable",[]).controller("AnimeTableCtrl",["$scope",function(a){this.animeList=a.animeList}]).directive("animeTableDir",function(){return{scope:{animeList:"=animeList"},restrict:"E",templateUrl:"animeListTable.html",replace:!1,controller:"AnimeTableCtrl",controllerAs:"ctrl"}});
angular.module("mangaList",[]).controller("MangaListCtrl",["$scope",function(a){a.card={name:"MangaList"};this.readingList=[{title:"Sakurasou no Pet na Kanojo",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shigatsu wa Kimi no Uso",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Horimiya",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Chikan Otoko",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.completedList=[{title:"Watashitachi no Shiawase na Jikan",
progress:"25/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Nisekoi",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Last Game",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Akagami no Shirayuki-hime",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tsurezure Children",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"To LOVE-Ru",progress:"3/3",type:"Tv",score:"-",season:"Fall 2015"}];this.droppedList=[{title:"Clannad",progress:"7/25",
type:"Tv",score:"10",season:"Fall 2015"},{title:"Toradora",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tonari no Kaibutsu-kun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Kiss x Sis",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.onholdList=[{title:"Sakamichi no Apollon",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shishunki Bitter Change",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Asobi ni Iku yo!",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Toaru Kagaku no Railgun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Yamada-kun to 7-nin no Majo",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Durarara!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.plantoreadList=[{title:"So Ra No Wo To",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Kanokon",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Octave",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Come Come Vanilla!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}]}]).directive("mangaListDir",function(){return{scope:{},restrict:"E",templateUrl:"mangaList.html",controller:"MangaListCtrl",controllerAs:"ctrl",replace:!0}});
angular.module("mangaTable",[]).controller("MangaTableCtrl",["$scope",function(a){this.mangaList=a.mangaList}]).directive("mangaTableDir",function(){return{scope:{mangaList:"=mangaList"},restrict:"E",templateUrl:"mangaListTable.html",replace:!0,controller:"MangaTableCtrl",controllerAs:"ctrl"}});
angular.module("menuDemoPosition",["ngMaterial"]).config(function(a){a.iconSet("hamburger","assets/svg/hamburger.svg",24).iconSet("social","img/icons/sets/social-icons.svg",24).defaultIconSet("/assets/svg/hamburger.svg",24)}).controller("PositionDemoCtrl",function(a){var b;this.openMenu=function(a,e){b=e;a(e)};this.announceClick=function(c){a.show(a.alert().title("You clicked!").content("You clicked the menu item at index "+c).ok("Nice").targetEvent(b));b=null}});
angular.module("chiika","ngMaterial md.data.table homePage animeList animeTable menuDemoPosition".split(" ")).config(function(a){a.theme("default").primaryPalette("teal").accentPalette("indigo")}).controller("AppCtrl",function(a,b){a.openLeftMenu=function(){b("left").toggle()}});
