'use strict';var ApiList=[{name:"ChiikaVerifyUser",index:0,argCount:1},{name:"ChiikaGetAnimelistRequest",index:1,argCount:0},{name:"ChiikaGetAnimelist",index:2,argCount:0}],ApiFuncCaller=function(){this.callApi=function(a,b,d,c,f){"undefined"===typeof ApiList[a]?console.log("Trying to call a API function that doesnt exist."):(console.log("Trying to execute"+ApiList[a].name+"... with arguments: "),console.log(c),"function"===typeof window[ApiList[a].name]?(console.log("Executing call..."+a),window[ApiList[a].name](b,
d,c)):console.log("You can't call this function outside of Chiika."))};this.updateAngularElement=function(a,b,d){angular.element(a).scope().updateAngularElement(b,d);angular.element(a).scope().$apply()}},apiFunctions;apiFunctions=new ApiFuncCaller;
var AnimeModel=function(){this.getSeason=function(){var a=this.startDate.split("-"),b=a[0],a=parseInt(a[1]);return 0<a&&4>a?"Winter "+b:3<a&&7>a?"Spring "+b:6<a&&10>a?"Summer "+b:9<a&&12>=a?"Fall "+b:"Unkown Season"};this.getStatus=function(){if("1"===this.status)return"Watching";if("2"===this.status)return"Completed";if("3"===this.status)return"On Hold";if("4"===this.status)return"Dropped";if("6"===this.status)return"Plan to Watch"};this.getType=function(){if("1"===this.type)return"Tv";if("2"===
this.type)return"Ova";if("3"===this.type)return"Movie"}},UserAnimeModel=function(){this.getProgressString=function(){return"0"===this.anime.episodeCount?"-":this.progress.value+"/"+this.anime.episodeCount};this.getScoreString=function(){return 0===this.score?"-":this.score}},AngularViewModel=function(){this.setModel=function(a){this.title=a.anime.title;this.progress=a.progress;this.progressString=a.getProgressString();this.type=a.anime.getType();this.score=a.score;this.scoreString=a.getScoreString();
this.season=a.anime.getSeason()}},UserAnimeList=function(){var a;this.getUserAnimeList=function(){return a};this.setUserAnimeList=function(b){a=b;console.log("Setting user anime list..size: "+a.length);console.log(a[0]);b=[];var d=[],c=0;for(c;c<a.length;c++){var f=a[c].my_status,e=new AnimeModel;e.title=a[c].anime.series_title;e.type=a[c].anime.series_type;e.status=a[c].series_status;e.startDate=a[c].anime.series_start;e.endDate=a[c].anime.series_end;e.episodeCount=a[c].anime.series_episodes;var g=
new UserAnimeModel;g.anime=e;g.progress={value:a[c].my_watched_episodes};g.score={value:a[c].my_score};e=new AngularViewModel;e.setModel(g);"1"===f&&b.push(e);"2"===f&&d.push(e)}console.log(b);apiFunctions.updateAngularElement($("#watchingWrapper"),b,1);apiFunctions.updateAngularElement($("#completedWrapper"),d,2)}},_userAnimeList;_userAnimeList=new UserAnimeList;
var User=function(){var a={watching:0,completed:0,onHold:0,dropped:0,planToWatch:0,daysSpent:0},b={reading:0,read:0,onHold:0,dropped:0,planToRead:0,daysSpent:0};this.getUserAnimeInfo=function(){return a};this.getUserMangaInfo=function(){return b}},Settings=function(){var a={startMinimized:!1,startWithWin:!1,rememberPos:!1,rememberSize:!1};this.getLibraryPath=function(){return""};this.getSyncInterval=function(){return 150};this.getWindowSettings=function(){return a};this.getGlobalColor=function(){}},
Chiika=function(){var a=this;a.getInitialized=function(){return!1};a.getSettings=function(){};a.getUserSettings=function(b){a.callApi("getUserSettings",b)};a.setUserSettings=function(b,d){a.callApi("setUserSettings",b,d)};a.getAnimeList=function(a,d){apiFunctions.callApi(1,this.handleAnimelistCallback,this.handleAnimelistError,"",!0)};a.callApi=function(a,d,c,f){apiFunctions.callApi(a,c,f,d,!1)};a.handleAnimelistCallback=function(a){_userAnimeList.setUserAnimeList(a[0])};a.handleAnimelistError=function(a){console.log(a)}},
chiika;chiika=new Chiika;$(document).ready(function(){chiika.getAnimeList()});
