'use strict';angular.module("homePage",[]).controller("HomePageCtrl",["$scope",function(a){a.card={name:"Episodes Watched"}}]).directive("homePageDir",function(){return{restrict:"E",templateUrl:"homepage.html"}});
angular.module("animeList",[]).controller("AnimeListCtrl",["$scope","$q","$timeout",function(a,c,d){a.selected=[];a.query={order:"title",limit:5,page:1};a.watchingList={count:4,data:[{title:"Owarimonogatari",progress:{value:.4},progressString:"7/25",type:"Tv",score:{value:8},season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:{value:.2},progressString:"2/25",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:{value:.75},progressString:"20/25",type:"Tv",score:"-",
season:"Fall 2015"},{title:"Gakusen Asterisk",progress:{value:.9},progressString:"24/25",type:"Tv",score:"-",season:"Fall 2015"}]};a.getTypes=function(){return["Tv"]};a.onpagechange=function(a,b){var e=c.defer();d(function(){e.resolve()},2E3);return e.promise};a.onorderchange=function(a){var b=c.defer();d(function(){b.resolve()},2E3);return b.promise}}]);
angular.module("animeTable",[]).controller("AnimeTableCtrl",["$scope",function(a){this.animeList=a.animeList}]).directive("animeTableDir",function(){return{scope:{animeList:"=animeList"},restrict:"E",templateUrl:"animeListTable.html",replace:!0,controller:"AnimeTableCtrl",controllerAs:"ctrl"}});
angular.module("mangaList",[]).controller("MangaListCtrl",["$scope",function(a){a.card={name:"MangaList"};this.readingList=[{title:"Sakurasou no Pet na Kanojo",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shigatsu wa Kimi no Uso",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Horimiya",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Chikan Otoko",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.completedList=[{title:"Watashitachi no Shiawase na Jikan",
progress:"25/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Nisekoi",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Last Game",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Akagami no Shirayuki-hime",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tsurezure Children",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"To LOVE-Ru",progress:"3/3",type:"Tv",score:"-",season:"Fall 2015"}];this.droppedList=[{title:"Clannad",progress:"7/25",
type:"Tv",score:"10",season:"Fall 2015"},{title:"Toradora",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tonari no Kaibutsu-kun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Kiss x Sis",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.onholdList=[{title:"Sakamichi no Apollon",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shishunki Bitter Change",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Asobi ni Iku yo!",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Toaru Kagaku no Railgun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Yamada-kun to 7-nin no Majo",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Durarara!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.plantoreadList=[{title:"So Ra No Wo To",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Kanokon",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Octave",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Come Come Vanilla!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}]}]).directive("mangaListDir",function(){return{scope:{},restrict:"E",templateUrl:"mangaList.html",controller:"MangaListCtrl",controllerAs:"ctrl",replace:!0}});
angular.module("mangaTable",[]).controller("MangaTableCtrl",["$scope",function(a){this.mangaList=a.mangaList}]).directive("mangaTableDir",function(){return{scope:{mangaList:"=mangaList"},restrict:"E",templateUrl:"mangaListTable.html",replace:!0,controller:"MangaTableCtrl",controllerAs:"ctrl"}});angular.module("chiikaAngular","ngMaterial md.data.table homePage animeList animeTable mangaList mangaTable".split(" "));
