'use strict';angular.module("homePage",[]).controller("HomePageCtrl",["$scope",function(a){a.card={name:"Episodes Watched"}}]).directive("homePageDir",function(){return{restrict:"E",templateUrl:"homepage.html"}});
angular.module("animeList",[]).controller("AnimeListCtrl",["$scope",function(a){a.card={name:"AnimeList"};this.watchingList=[{title:"Owarimonogatari",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Rakudai Kishi no Cavalary",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami Aragoto",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Gakusen Asterisk",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.completedList=[{title:"Suzumiya Haruhi no Yuuutsu",
progress:"25/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Code Geass: Hangyaku no Lelouch",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Noragami",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Byousoku 5 Centimeter",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Toki wo Kakeru Shoujo",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"To LOVE-Ru",progress:"3/3",type:"Tv",score:"-",season:"Fall 2015"}];this.droppedList=[{title:"Clannad",
progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Toradora",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Ga-Rei: Zero",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Kiss x Sis",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.onholdList=[{title:"Higashi no Eden",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Sora no Otoshimono",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Asobi ni Iku yo!",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Toaru Kagaku no Railgun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Chuu Bra!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Durarara!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.plantowatchList=[{title:"So Ra No Wo To",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Working!!!!!!!!!!!!!!!!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Aki-Sora",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Suzumiya Haruhi no Shoushitsu",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}]}]).directive("animeListDir",function(){return{scope:{},restrict:"E",templateUrl:"animeList.html",controller:"AnimeListCtrl",controllerAs:"ctrl",replace:!0}});
angular.module("animeTable",[]).controller("AnimeTableCtrl",["$scope",function(a){this.animeList=a.animeList}]).directive("animeTableDir",function(){return{scope:{animeList:"=animeList"},restrict:"E",templateUrl:"animeListTable.html",replace:!0,controller:"AnimeTableCtrl",controllerAs:"ctrl"}});
angular.module("mangaList",[]).controller("MangaListCtrl",["$scope",function(a){a.card={name:"MangaList"};this.readingList=[{title:"Sakurasou no Pet na Kanojo",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shigatsu wa Kimi no Uso",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Horimiya",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Chikan Otoko",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.completedList=[{title:"Watashitachi no Shiawase na Jikan",
progress:"25/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Nisekoi",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Last Game",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Akagami no Shirayuki-hime",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tsurezure Children",progress:"12/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"To LOVE-Ru",progress:"3/3",type:"Tv",score:"-",season:"Fall 2015"}];this.droppedList=[{title:"Clannad",progress:"7/25",
type:"Tv",score:"10",season:"Fall 2015"},{title:"Toradora",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Tonari no Kaibutsu-kun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Kiss x Sis",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.onholdList=[{title:"Sakamichi no Apollon",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Shishunki Bitter Change",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Asobi ni Iku yo!",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Toaru Kagaku no Railgun",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Yamada-kun to 7-nin no Majo",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Durarara!!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}];this.plantoreadList=[{title:"So Ra No Wo To",progress:"7/25",type:"Tv",score:"10",season:"Fall 2015"},{title:"Kanokon",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"},{title:"Octave",progress:"7/12",
type:"Tv",score:"-",season:"Fall 2015"},{title:"Come Come Vanilla!",progress:"7/12",type:"Tv",score:"-",season:"Fall 2015"}]}]).directive("mangaListDir",function(){return{scope:{},restrict:"E",templateUrl:"mangaList.html",controller:"MangaListCtrl",controllerAs:"ctrl",replace:!0}});
angular.module("mangaTable",[]).controller("MangaTableCtrl",["$scope",function(a){this.mangaList=a.mangaList}]).directive("mangaTableDir",function(){return{scope:{mangaList:"=mangaList"},restrict:"E",templateUrl:"mangaListTable.html",replace:!0,controller:"MangaTableCtrl",controllerAs:"ctrl"}});angular.module("chiikaAngular",["homePage","animeList","animeTable","mangaList","mangaTable"]);
